### ISSUE TITLE
SetDoNotParseResponse

### ISSUE THREAD

**Issue by jhemmmm** [monaco-io/request#18]
Hello,

Is there any options or settings similar to "SetDoNotParseResponse"

**Comment by luxuze** [comment]
if you want to get original body, you can call Bytes() function. and call Response() to get *http.Response

**Comment by jhemmmm** [comment]
> if you want to get original body, you can call Bytes() function. and call Response() to get *http.Response

I am not that familiar with golang but, isn't piping a data looks like this?.
```
io.Copy(w, resp.Response().Body)
```

Doing that returns an empty file.

**Comment by luxuze** [comment]
> > if you want to get original body, you can call Bytes() function. and call Response() to get *http.Response
> 
> I am not that familiar with golang but, isn't piping a data looks like this?.
> 
> ```
> io.Copy(w, resp.Response().Body)
> ```
> 
> Doing that returns an empty file.
```go
bodyBytes := resp.Bytes()
```
