### ISSUE TITLE
Allowing modification of http.client

### ISSUE THREAD

**Issue by margolisj** [monaco-io/request#5]
Hey, I am trying to pass in a non default http client. Similar to something like this:

```go
defaultRoundTripper := http.DefaultTransport
  defaultTransportPointer, ok := defaultRoundTripper.(*http.Transport)
  if !ok {
      panic(fmt.Sprintf("defaultRoundTripper not an *http.Transport"))
  }
  defaultTransport := *defaultTransportPointer // dereference it to get a copy of the struct that the pointer points to
  defaultTransport.MaxIdleConns = 100
  defaultTransport.MaxIdleConnsPerHost = 100

  myClient = &http.Client{Transport: &defaultTransport}
```

I don't see any way that is obvious but I'm open to making some minor changes, for example making it public public in the request.Client struct. Is there a way that would make sense to you and I could submit a PR?

**Comment by luxuze** [comment]
You can add a transport option in struct Client, and add a func to apply the transport. Submit a pull request at will.

**Comment by margolisj** [comment]
Completed here: https://github.com/monaco-io/request/pull/6
