### ISSUE TITLE
AMAZING PROJECT I LOVE IT SO MUCH!!!!!

### ISSUE THREAD

**Issue by bgbusted** [monaco-io/request#8]
Its the best request library right now 
https://gist.github.com/bgbusted/698a76a42794364238ed0eb2b91e6186

my issue is one thing the  HEADERs goes by the ABC ?
how can I make it like chrome ?
![image](https://user-images.githubusercontent.com/78641282/107117817-84a0c580-6885-11eb-8f1d-5435db65bba0.png)

I already got the fingerprint done but I still have issues with the headers its not as it is on chrome :)

**Comment by luxuze** [comment]
v1.0.8

You can define the http header:

```go
client := request.Client{
        URL:    "https://google.com",
        Method: "POST",
       Header: map[string]string{"Cache-Control": "no-cache", ...},
 }
resp := client.Send()
if resp.OK(){
...
}
```

**Comment by bgbusted** [comment]
> v1.0.8
> 
> You can define the http header:
> 
> ```go
> client := request.Client{
>         URL:    "https://google.com",
>         Method: "POST",
>        Header: map[string]string{"Cache-Control": "no-cache", ...},
>  }
> resp := client.Send()
> if resp.OK(){
> ...
> }
> ```

I have an issue with uTLS with the header Accept-Encoding: gzip
should be except uTLS support ? https://gitlab.com/yawning/utls

**Comment by luxuze** [comment]
> > v1.0.8
> > You can define the http header:
> > ```go
> > client := request.Client{
> >         URL:    "https://google.com",
> >         Method: "POST",
> >        Header: map[string]string{"Cache-Control": "no-cache", ...},
> >  }
> > resp := client.Send()
> > if resp.OK(){
> > ...
> > }
> > ```
> 
> I have an issue with uTLS with the header Accept-Encoding: gzip
> should be except uTLS support ? https://gitlab.com/yawning/utls for ClientHello...
> check my source at
> https://gist.github.com/bgbusted/698a76a42794364238ed0eb2b91e6186

According to net/http docs ([line 110](https://golang.org/src/net/http/transport.go#L110)) if you manually set the Accept-Encoding request header, than gzipped response will not automatically decompressed by the http.Transport. Otherwise, behavior is controlled by the Transport's DisableCompression boolean

**Comment by bgbusted** [comment]
> > > v1.0.8
> > > You can define the http header:
> > > ```go
> > > client := request.Client{
> > >         URL:    "https://google.com",
> > >         Method: "POST",
> > >        Header: map[string]string{"Cache-Control": "no-cache", ...},
> > >  }
> > > resp := client.Send()
> > > if resp.OK(){
> > > ...
> > > }
> > > ```
> > 
> > 
> > I have an issue with uTLS with the header Accept-Encoding: gzip
> > should be except uTLS support ? https://gitlab.com/yawning/utls for ClientHello...
> > check my source at
> > https://gist.github.com/bgbusted/698a76a42794364238ed0eb2b91e6186
> 
> According to net/http docs ([line 110](https://golang.org/src/net/http/transport.go#L110)) if you manually set the Accept-Encoding request header, than gzipped response will not automatically decompressed by the http.Transport. Otherwise, behavior is controlled by the Transport's DisableCompression boolean

Thank you so much! But I have an issue with making it by order just like chrome 
the CanonicalHeaderKey makes my headers goes by the ABC or something, how do I set ""type Header map[string][]string"" to have the headers by my order?

**Comment by bgbusted** [comment]
![image](https://user-images.githubusercontent.com/78641282/107317043-93b08f00-6aa2-11eb-8735-83a74a176de3.png)

**Comment by bgbusted** [comment]
![image](https://user-images.githubusercontent.com/78641282/107324061-083dfa80-6ab0-11eb-9032-be77ac72e6a1.png)

**Comment by luxuze** [comment]
@bgbusted ok, i will release a new version to support this today.

**Comment by luxuze** [comment]
@bgbusted upgrade to v1.0.9

**Comment by luxuze** [comment]
<img width="586" alt="image" src="https://user-images.githubusercontent.com/35137889/107327937-e90f8f00-6ae8-11eb-927b-f19b51d33307.png">
